/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alejandro_unizar_mobilecv_NativeClass */

#ifndef _Included_com_alejandro_unizar_mobilecv_NativeClass
#define _Included_com_alejandro_unizar_mobilecv_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    ProcImage
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_ProcImage
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    initRecognizer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_initRecognizer
  (JNIEnv *, jclass);

/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    FindObjects
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_FindObjects
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    doTest
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_doTest
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    startClient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_startClient
  (JNIEnv *, jclass);

/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    sendRemote
 * Signature: (II[B[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_sendRemote
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    endClient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_endClient
  (JNIEnv *, jclass);

/*
 * Class:     com_alejandro_unizar_mobilecv_NativeClass
 * Method:    showStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alejandro_unizar_1mobilecv_NativeClass_showStats
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
