/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alejandro_nativeopencv_NativeClass */

#ifndef _Included_com_alejandro_nativeopencv_NativeClass
#define _Included_com_alejandro_nativeopencv_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alejandro_nativeopencv_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alejandro_nativeopencv_NativeClass_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
