/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alejandro_nativeopencv_NativeClass */

#ifndef _Included_com_alejandro_nativeopencv_NativeClass
#define _Included_com_alejandro_nativeopencv_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alejandro_nativeopencv_NativeClass
 * Method:    ProcImage
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_nativeopencv_NativeClass_ProcImage
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_alejandro_nativeopencv_NativeClass
 * Method:    loadImages
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_nativeopencv_NativeClass_loadImages
  (JNIEnv *, jclass);

/*
 * Class:     com_alejandro_nativeopencv_NativeClass
 * Method:    FindObjects
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_alejandro_nativeopencv_NativeClass_FindObjects
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
